objects/Exception_Log__c.object
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EX-{000000}</displayFormat>
        <label>Exception Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Exception_Logging__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Description_Max__c</fullName>
        <label>Exception Description Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exception_Details_Max__c</fullName>
        <inlineHelpText>Max length of exception details</inlineHelpText>
        <label>Exception Details Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exception_Logs_Purge_Days__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Exception Logs Purge (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Info__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logging_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Logging Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warning__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Warning</label>
        <type>Checkbox</type>
    </fields>
    <label>Exception Logging</label>
</CustomObject>

objects/Integration_Log__c.object
<CustomObject>
    <description>This object is used for logging all web service calls made into salesforce from external systems.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <recordTypes>
        <fullName>INBOUND</fullName>
        <active>true</active>
        <description>Record Type for any inbound web service calls</description>
        <label>INBOUND</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Logging__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Integration_Logs_Purge_Days__c</fullName>
        <label>Integration Logs Purge Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Logging_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Logging Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_Load_Max__c</fullName>
        <label>Pay Load Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Logging</label>
</CustomObject>

classes/PurgeLogSchedulerTest.cls
/**
  * @author        Saumil Bapat
  * @date          10/31/2016
  * @description   Test class for PurgeLogs batch jobs
*/
@isTest
private class PurgeLogSchedulerTest {

   // CRON expression: midnight on March 15.
   // Because this is a test, job executes
   // immediately after Test.stopTest().
   public static String CRON_EXP = '0 0 0 15 3 ? 2050';

   static testmethod void testScheduledPurgeLogs() {

     //Initialize the custom settings records
     initializeCustomSettings();

      /*Create Integration Log*/
      UTIL_Logging.integrationLogId = UTIL_Logging.createIntegrationLog(
                                                         'INBOUND',
                                                         'Test Payload',
                                                         'Test Process Name',
                                                         'Test Source Name',
                                                         'Test Transaction Id'
                                                       );

      /*Create Exception Logs*/
      //Initialize list of exception logs
      List<UTIL_Logging.ExceptionLog> logs = new List<UTIL_Logging.ExceptionLog>();

      //Create 10 Exception log records
      for (Integer i=1; i<=10; i++) {

         //Initialize a custom mapping exception
         Exception e = UTIL_Logging.createMappingException(
            'Test Mapping Error: ' + +' ' + String.ValueOf(i)
         );

         //Create a exception log record
         UTIL_Logging.ExceptionLog log = new UTIL_Logging.ExceptionLog(
            e,
            'PurgeLogSchedulerTest',
            'testScheduledPurgeLogs',
            '',
            'Error'
         );

         //add exception log to list
         logs.add(log);
      }

      //Insert exception logs
      UTIL_Logging.logExceptions(logs);

      // Verify the integration logs have been created
      List<Integration_Log__c> integrationLogs = [SELECT Id FROM Integration_Log__c];
      System.assertEquals(integrationLogs.size(),1);

      //Verify the exception logs have been created
      List<Exception_Log__c> exceptionLogs = [SELECT Id FROM Exception_Log__c];
      System.assertEquals(exceptionLogs.size(),10);

      //Initiate the scheduled & batch purge jobs
      Test.startTest();

      // Schedule the test job
      String jobId = System.schedule('testScheduledPurgeLogs', CRON_EXP, new PurgeLogScheduler());

      // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same
      System.assertEquals(CRON_EXP, ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run
      System.assertEquals('2050-03-15 00:00:00', String.valueOf(ct.NextFireTime));

      //Process the scheduled & batch purge jobs
      Test.stopTest();
   }

   private static void initializeCustomSettings()
   {
     //Create exception logging Custom Setting Record
     Exception_Logging__c exceptionParams = new Exception_Logging__c(
                                                             Exception_Description_Max__c = 255,
                                                             Exception_Details_Max__c = 255,
                                                             Exception_Logs_Purge_Days__c = 30,
                                                             Logging_Enabled__c = true,
                                                             Info__c = true,
                                                             Warning__c = true,
                                                             Debug__c = true,
                                                             Error__c = true
                                                         );
     //insert Exception_Logging__c
     insert exceptionParams;

     //Create integration log custom setting record
     Integration_Logging__c integrationParams = new Integration_Logging__c(
                                                     Integration_Logs_Purge_Days__c = 30,
                                                     Logging_Enabled__c = true,
                                                     Pay_Load_Max__c = 100000
                                                       );

     //insert Integration_Logging__c
     insert integrationParams;
   }
}