objects/Exception_Log__c.object
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EX-{000000}</displayFormat>
        <label>Exception Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Exception_Logging__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Exception_Logs_Purge_Days__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Exception Logs Purge (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Exception Logging</label>
</CustomObject>

objects/Integration_Log__c.object
<CustomObject>
    <description>This object is used for logging all web service calls made into salesforce from external systems.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Logging__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Integration_Logs_Purge_Days__c</fullName>
        <label>Integration Logs Purge Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Logging</label>
</CustomObject>

classes/PurgeLogs.cls
/**
  * @author        Saumil Bapat
  * @date          10/28/2016
  * @description   批处理类删除老日志
*/
global class PurgeLogs implements Database.Batchable<sObject>
{
   //删除日志的类型
   global enum LogType{INTEGRATION_LOG, EXCEPTION_LOG}

   //查询日志删除
   global String query;

   //查询日志删除
   global LogType type;

   //构造函数
   global PurgeLogs(LogType type)
   {
      //获取异常日志的设置
      Exception_Logging__c exceptionParams = Exception_Logging__c.getInstance();

      //获取集成日志的设置
      Integration_Logging__c integrationParams = Integration_Logging__c.getInstance();
      
      if (type == LogType.INTEGRATION_LOG)
      {
         this.query = 'Select Id from Integration_Log__c where LastModifiedDate != LAST_N_DAYS:' + integrationParams.Integration_Logs_Purge_Days__c;
         this.type = LogType.INTEGRATION_LOG;
      }
      if (type == LogType.EXCEPTION_LOG)
      {
         this.query = 'Select Id from Exception_Log__c where LastModifiedDate != LAST_N_DAYS:' + exceptionParams.Exception_Logs_Purge_Days__c;
         this.type = LogType.EXCEPTION_LOG;
      }
   }

   //Start method for the batch
   global Database.QueryLocator start(Database.BatchableContext BC)
   {
      return Database.getQueryLocator(query);
   }

   //Execute method for the batch
   global void execute(Database.BatchableContext BC,List<SObject> scope)
   {
      delete scope;
   }

   //Finish method for the batch
   global void finish(Database.BatchableContext BC){}
}